### ISSUE TITLE
Crashes on Windows Nvidia driver..

### ISSUE THREAD

**Issue by oscarbg** [alexhultman/libvc#3]
I just downloaded a zipped copy of master branch a week ago and created Visual Studio project.. fixed link pointing to spv shader file but still crashes at:
" if (VK_SUCCESS != vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr, &pipeline)) {"
have you tested on Windows?
Specs:
GTX970 running Nv driver 364.47
Windows 10 Nov update TH1
VS 2015.1

**Comment by ghost** [comment]
You should probably update to the latest commit then. It was broken a week ago (the shader expected buffers to be bound, but the pipeline wasn't created with a descriptor set that matched). It also crashed on Linux at that time.

I don't have Windows other than a VM that I used to build a Windows version but I cannot run it lol.

**Comment by ghost** [comment]
HEY! Could you compile the case1_opencl for me? NVIDIA wants it.

**Comment by oscarbg** [comment]
leave some days.. crazy busy following GDC news..

**Comment by ghost** [comment]
What did I miss?
